# Images yang digunakan sebagai base image dengan os alpine
FROM node:18-alpine as build

# Set working directory di dalam container
WORKDIR /app

# Copy file package.json ke working directory
COPY package*.json ./

# Install dependencies
RUN npm install


# Copy semua file dari host ke working directory di dalam container
FROM node:18-alpine as production

# Set working directory di dalam container
WORKDIR /app

# Copy hanya node_modules dari tahap build
COPY --from=build /app/node_modules ./node_modules

# Copy semua file dari host ke working directory di dalam container
COPY . .

# Expose port yang akan digunakan oleh aplikasi
EXPOSE 3000

# Perintah untuk menjalankan aplikasi
CMD ["npm", "start"]